language: c

# explicitly request container-based infrastructure
sudo: false

env:
  matrix:
    - GHCVER=7.10.3

  global:
    secure: "kbkJf+ukAlZMIcbTD/jIGt6p51nkm2VERZ7jHKQ0betHPyQtBz7Ly43bge4oggRP6s9cDoobFSMendQHTuV5Kyv+BHnQTBpReryOzFMqP3Bm0ZGlZzbn+v2Z1HisDIHGK2kLk3iQyO4S8+Pc/yqbJYVf4iUxh+tUoB11/aCmE3k="


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - hvr-ghc
    - ubuntu-toolchain-r-test
# blocked by https://github.com/travis-ci/apt-source-whitelist/issues/149
#            https://github.com/travis-ci/apt-source-whitelist/pull/150
#    - chris-lea/zeromq

    packages:
    - cabal-install-1.24
    - ghc-7.10.3
    - pkg-config
    - libglpk-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - freeglut3-dev
    - libglib2.0-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libgtk2.0-dev
    - libgsl0-dev
    - liblapack-dev
    - libblas-dev
    - coinor-libipopt-dev
    - libmumps-dev
    - libmumps-seq-dev
    - gcc-4.8
    - happy-1.19.4
    - alex-3.1.3
    - gcc
    - g++
    - gfortran
    - git
    - cmake
# blocked by https://github.com/travis-ci/apt-source-whitelist/issues/149
#            https://github.com/travis-ci/apt-source-whitelist/pull/150
#    - libzmq3-dev=4.0.5-1chl1~precise1


before_install:
 # Download and unpack the stack executable
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - chmod a+x ~/.local/bin/stack

 # haskell deps
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

  # ipopt
 - export IPOPT_DEFAULT_LINEAR_SOLVER=ma57
 - export LD_LIBRARY_PATH=/home/travis/build/libhsl

   # hsl linear solvers
 - pushd ../../ && git clone https://github.com/casadi/testbot.git
 - pushd testbot && recipes/setup.sh && popd
 - travis_retry testbot/recipes/fetch.sh libhsl.tar.gz && mkdir libhsl && tar -xvf libhsl.tar.gz -C libhsl
 - mkdir -p /home/travis/build/casadi/testbot
 - ls -al
 - popd

   # casadi from source:
 - cd ..
 - git clone https://github.com/casadi/casadi.git
 - cd casadi
 - mkdir build
 - cd build
 - cmake -DCMAKE_INSTALL_PREFIX=~/casadi_install -DWITH_EXAMPLES=OFF ..
 - make -j4
 - make install
 - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/casadi_install/lib/pkgconfig
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/casadi_install/lib
 - cd ../../dynobud
#   # casadi from .deb
## - wget http://github.com/casadi/casadi/releases/download/2.2.0/libcasadi-shared-2.2.0-x86_64.deb
# - wget http://sourceforge.net/projects/casadi/files/CasADi/2.3.0/linux/libcasadi-v2.3.0.deb
# - sudo dpkg -i libcasadi-v2.3.0.deb
# - sudo apt-get install -f
# - rm libcasadi-v2.3.0.deb

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

script:
  - stack build --no-terminal --test
