language: c

# explicitly request container-based infrastructure
sudo: false

env:
  global:
    secure: "kbkJf+ukAlZMIcbTD/jIGt6p51nkm2VERZ7jHKQ0betHPyQtBz7Ly43bge4oggRP6s9cDoobFSMendQHTuV5Kyv+BHnQTBpReryOzFMqP3Bm0ZGlZzbn+v2Z1HisDIHGK2kLk3iQyO4S8+Pc/yqbJYVf4iUxh+tUoB11/aCmE3k="


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/casadi_install

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
# blocked by https://github.com/travis-ci/apt-source-whitelist/issues/149
#            https://github.com/travis-ci/apt-source-whitelist/pull/150
#    - chris-lea/zeromq

    packages:
    - pkg-config
    - libgmp-dev
    - libglpk-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - freeglut3-dev
    - libglib2.0-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libgtk-3-dev
    - libgsl0-dev
    - liblapack-dev
    - libblas-dev
    - coinor-libipopt-dev
    - libmumps-dev
    - libmumps-seq-dev
    - gcc-4.8
    - g++-4.8
    - gfortran-4.8
    - git
    - cmake
    - libzmq3
    - libzmq3-dev
# blocked by https://github.com/travis-ci/apt-source-whitelist/issues/149
#            https://github.com/travis-ci/apt-source-whitelist/pull/150
#    - libzmq3-dev=4.0.5-1chl1~precise1


before_install:
 # Download and unpack the stack executable
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - chmod a+x ~/.local/bin/stack

 # ipopt / hsl
 - export IPOPT_DEFAULT_LINEAR_SOLVER=ma57
 - pushd ../../ && git clone https://github.com/casadi/testbot.git
 - pushd testbot && source recipes/setup.sh && popd
 - export SLURP_OS=trusty
 - slurp hsl
 - mkdir -p /home/travis/build/casadi/testbot
 - ls -al
 - popd

   # casadi from source:
 - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/casadi_install/lib/pkgconfig
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/casadi_install/lib
 - pushd ..
 - if pkg-config --exists "casadi >= 3.0.0"; then echo "existing casadi detected"; else ./dynobud/travis/install_casadi; fi
 - popd

install:
  - stack setup --no-terminal
  # workaround for getting stack to use gcc 4.8
  # - stack build --with-gcc=/usr/bin/gcc-4.8 --flag dynobud:-examples --no-terminal --only-snapshot
  - stack build --flag dynobud:-examples --with-gcc=/usr/bin/gcc-4.8 --no-terminal --only-snapshot

script:
  - stack build --flag dynobud:-examples --with-gcc=/usr/bin/gcc-4.8 --no-terminal --test
