# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-10.2

compiler-check: newer-minor

# Local packages, usually specified by relative directory name
packages:
- .

- location:
    git: https://github.com/ghorn/casadi-bindings
    commit: ee999a2f3dec1bb815929b63d6d3de51eedd4214
  extra-dep: true
  subdirs:
  - casadi-bindings
  - casadi-bindings-internal
  - genpath/casadi-bindings-core

# - location:
#     git: https://github.com/ghorn/generic-accessors
#     commit: 393a9c8660010580c513eb75408b0507b6ded33d
#   extra-dep: true

#- location:
#    git: https://github.com/ghorn/Plot-ho-matic
#    commit: c18883ba529187c448fe6cc144dad323e78c41c2
#  extra-dep: true

#- location:
##    git: /home/greghorn/hslibs/Plot-ho-matic
#    git: https://github.com/ghorn/Plot-ho-matic
#    commit: e148ad3ec9603ed3694ea709c6e01b7d4670ff88
#  extra-dep: true

#- location:
#    git: https://github.com/ghorn/spatial-math
#    commit: 289ab9159b9813a8f8de06d4ff6f28ec445bed6e
#  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ # casadi-bindings-3.1.0.22
            # , casadi-bindings-core-3.1.0.22
            # , casadi-bindings-internal-0.1.5.0
              generic-accessors-0.7.0.0
            , gtk3-0.14.8
            , gio-0.13.4.1
            , jacobi-roots-0.2.0.4
            , not-gloss-0.7.6.5
            , Plot-ho-matic-0.12.2.2
            , spatial-math-0.4.0.0
            , TypeCompose-0.9.12
            , vector-binary-instances-0.2.1.0
            ]

# Override default flag values for local packages and extra-deps
flags:
  dynobud:
    examples: true
